### ISSUE TITLE
installation on windows

### ISSUE THREAD

**Issue by vshl-ptl** [fpdetective/fpdetective#2]
I have read your paper : FPDetective: Dusting the Web for Fingerprinters and I would like to do the same experiment using the framework. For that I have followed instructions on https://github.com/fpdetective/fpdetective. I am using windows machine. 

I have done following :
-Downloaded and extracted fpdetective in C drive.
-Installed vagrant and virtualbox.
-Run command ‘vagrant up’ in C:\fpdetective-master\vm\GUI directory. As the result of this command, I got virtualbox running with vagrant guest user. I provided ‘vagrant’ password as per the installation instructions.

What should I do from now on?

**Comment by gunesacar** [comment]
Hi,

First you need to [run a crawl](https://github.com/fpdetective/fpdetective#how-to-launch-a-simple-crawl) to collect data. I suggest first running [tests](https://github.com/fpdetective/fpdetective/blob/master/src/crawler/test/run_all_tests.sh) and test crawls to make sure that everything works.

Then you should check the database for the results. `fp_detected` column of the `site_info` table would give the detected fingerprinters that are already  [known by fpdetective](https://github.com/fpdetective/fpdetective/blob/master/src/crawler/fp_regex.py). Since that list is pretty outdated and scripts change fast, you better check the database yourself to find new fingerprinting scripts. Please check `num_font_loads`,  `num_offsetWidth_calls` and `num_offsetHeight_calls` columns of the `js_info` table for possible signs of font probing (e.g. `num_font_loads > 30` and `num_offsetWidth_calls > 30` or `num_offsetWidth_calls > 30`). You may also need the check the logs (`site_crawl_log`,  `fpd_logs`) to see whether other browser properties (screen dimensions, plugins etc.) accessed by the same script (or other scripts from the same domain.) If Flash was enabled in your crawls, you may also check `swf_obj` table (esp. `occ_string` column) for [fingerprinting related ActionScript calls](https://github.com/fpdetective/fpdetective/blob/3912a814d11f340db9517a52f1298f588f37dbc9/src/crawler/swfutils.py#L13).

I'll try to put some documentation for the analysis of the data collected by fpdetective but cannot promise anything for the near future. Feel free to open issues or reach directly for any problems you're having.

**Comment by vshl-ptl** [comment]
HI 

I ran test crawl and got some errors which are as below:

======================================================================
ERROR: test_casper_bin (__main__.RunEnvTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runenv_test.py", line 22, in test_casper_bin
    self.should_be_executable(cm.CASPER_BINARY)
AttributeError: 'RunEnvTest' object has no attribute 'should_be_executable'

======================================================================
ERROR: test_chrome_driver_bin (__main__.RunEnvTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runenv_test.py", line 25, in test_chrome_driver_bin
    self.should_be_executable(cm.CHROME_DRIVER_BINARY)
AttributeError: 'RunEnvTest' object has no attribute 'should_be_executable'

======================================================================
ERROR: test_chrome_mod_bin (__main__.RunEnvTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runenv_test.py", line 13, in test_chrome_mod_bin
    self.should_be_executable(cm.CHROME_MOD_BINARY)
AttributeError: 'RunEnvTest' object has no attribute 'should_be_executable'

======================================================================
ERROR: test_phantom_bin (__main__.RunEnvTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runenv_test.py", line 16, in test_phantom_bin
    self.should_be_executable(cm.PHANTOM_BINARY)
AttributeError: 'RunEnvTest' object has no attribute 'should_be_executable'

======================================================================
ERROR: test_phantom_mod_bin (__main__.RunEnvTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "runenv_test.py", line 19, in test_phantom_mod_bin
    self.should_be_executable(cm.PHANTOM_MOD_BINARY)
AttributeError: 'RunEnvTest' object has no attribute 'should_be_executable'

======================================================================
FAIL: test_default_settings (__main__.AgentTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "agents_test.py", line 68, in test_default_settings
    self.should_crawl_and_log({}, urls, expected_strs)
  File "/home/vagrant/fpdetective/src/crawler/test/fpdtest.py", line 106, in should_crawl_and_log
    self.assert_all_patterns_in_file(outfile, expected_strs)
  File "/home/vagrant/fpdetective/src/crawler/test/fpdtest.py", line 73, in assert_all_patterns_in_file
    self.fail("Cannot find pattern %s in %s" % (pat, filename))
AssertionError: Cannot find pattern FontFaceName in /home/vagrant/fpbase/run/jobs/20150411-032812/1-file-home-vagrant-fpbase-src-crawler-test-files-font-face-font-face-names-html.txt

======================================================================
FAIL: test_should_click_fp_related_links (__main__.CasperTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "casper_test.py", line 29, in test_should_click_fp_related_links
    urls, expected_url_strings + CASPER_CLICK_LOGS, COMMON_CASPER_ERROR_LOGS)
  File "/home/vagrant/fpdetective/src/crawler/test/fpdtest.py", line 106, in should_crawl_and_log
    self.assert_all_patterns_in_file(outfile, expected_strs)
  File "/home/vagrant/fpdetective/src/crawler/test/fpdtest.py", line 73, in assert_all_patterns_in_file
    self.fail("Cannot find pattern %s in %s" % (pat, filename))
AssertionError: Cannot find pattern html#linkx1 in /home/vagrant/fpbase/run/jobs/20150411-033230/1-file-home-vagrant-fpbase-src-crawler-test-files-crawler-fp_links-html.txt

======================================================================
ERROR: test_should_timeout_onbeforeunload (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "chrome_test.py", line 29, in test_should_timeout_onbeforeunload
    cr.crawl_url("chrome_clicker", test_url, "")
  File "/home/vagrant/fpdetective/src/crawler/crawler.py", line 129, in crawl_url
    '--enable-logging', '--v=1', "--proxy-server=%s" % proxy_opt])
  File "/home/vagrant/fpdetective/src/crawler/crawler.py", line 44, in init_browser
    chrome_options=ch)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 65, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 74, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 123, in start_session
    'desiredCapabilities': desired_capabilities,
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 175, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.5.231443,platform=Linux 3.2.0-55-generic x86_64)

======================================================================
FAIL: test_should_create_out_file (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "mitm_test.py", line 47, in test_should_create_out_file
    self.assert_is_file(mitmcfg.dmpfile, "Output file %s is missing, cannot start mitmdump with default port" % mitmcfg.dmpfile)
  File "/home/vagrant/fpdetective/src/crawler/test/fpdtest.py", line 54, in assert_is_file
    self.assertTrue(os.path.isfile(filename), msg)
AssertionError: Output file /tmp/mitmout.dmp is missing, cannot start mitmdump with default port

----------------------------------------------------------------------

======================================================================
FAIL: test_modchrome_should_log_access_to_navigator_props (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "mod_chromium_test.py", line 28, in test_modchrome_should_log_access_to_navigator_props
    self.should_log_access_to_navigator_props(cr.__dict__, expected)
  File "mod_chromium_test.py", line 52, in should_log_access_to_navigator_props
    self.assert_all_patterns_in_file(self.log_file, expected_strs+expected_log_strs)
  File "/home/vagrant/fpdetective/src/crawler/test/fpdtest.py", line 73, in assert_all_patterns_in_file
    self.fail("Cannot find pattern %s in %s" % (pat, filename))
AssertionError: Cannot find pattern DOMMimeType::suffixes:swf in /tmp/browser_test.log

----------------------------------------------------------------------

**Comment by gunesacar** [comment]
Thanks for reporting!
[This commit](https://github.com/fpdetective/fpdetective/commit/420fd59a84085fc06370d89e2fccf02b8b0c35b8) should address the 5 of the above errors (due to missing `should_be_executable` function).
Can you please run the tests again and open specific issues if you get any errors?
I see errors due to incompatibilities such as the one with the ChromeDriver.
I may need to update many of the software and libraries.
